project:
  type: website
  render:
    - index.qmd
    - lessons.qmd
    - LESSONS/COMPLETED/*.qmd
    - NOTES/*.qmd
  output-dir: docs

website:
  title: "ITMAT office houRs"
  back-to-top-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Overview
      - href: lessons.qmd
        text: Lessons

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
